services:
  - type: web
    name: mams-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: APP_CORS_ALLOWED_ORIGINS
        sync: false
      - key: SERVER_SERVLET_SESSION_COOKIE_SAMESITE
        value: none
      - key: SERVER_SERVLET_SESSION_COOKIE_SECURE
        value: "true"
