-- H2 2.2.224; 
;              
CREATE USER IF NOT EXISTS "SA" SALT 'a88794f8554239cb' HASH 'f6eabd24211aaa1f82db35d1b2d21897f0df0aed7c2af790c38958f46f2bdff0' ADMIN;          
CREATE CACHED TABLE "PUBLIC"."ASSIGNMENTS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 19) NOT NULL,
    "ASSIGNED_DATE" DATE NOT NULL,
    "CREATED_AT" TIMESTAMP(6) NOT NULL,
    "CREATED_BY" CHARACTER VARYING(255) NOT NULL,
    "PERSONNEL_NAME" CHARACTER VARYING(255) NOT NULL,
    "QUANTITY" INTEGER NOT NULL,
    "RETURNED_DATE" DATE,
    "STATUS" ENUM('ACTIVE', 'RETURNED') NOT NULL,
    "BASE_ID" BIGINT NOT NULL,
    "EQUIPMENT_TYPE_ID" BIGINT NOT NULL
); 
ALTER TABLE "PUBLIC"."ASSIGNMENTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("ID");   
-- 18 +/- SELECT COUNT(*) FROM PUBLIC.ASSIGNMENTS;             
INSERT INTO "PUBLIC"."ASSIGNMENTS" VALUES
(1, DATE '2026-05-13', TIMESTAMP '2026-05-13 14:42:00', 'cmdr_alpha', 'Lt. K. Mehta', 3, NULL, 'ACTIVE', 1, 1),
(2, DATE '2026-06-18', TIMESTAMP '2026-06-18 17:44:00', 'cmdr_bravo', 'Pvt. A. Khan', 7, NULL, 'ACTIVE', 3, 4),
(3, DATE '2026-03-03', TIMESTAMP '2026-03-03 15:23:00', 'cmdr_alpha', 'Pvt. A. Khan', 5, NULL, 'ACTIVE', 1, 1),
(4, DATE '2025-10-29', TIMESTAMP '2025-10-29 13:19:00', 'admin', 'Lt. K. Mehta', 3, NULL, 'ACTIVE', 1, 4),
(5, DATE '2025-11-30', TIMESTAMP '2025-11-30 17:42:00', 'admin', 'Sgt. J. Rao', 4, NULL, 'ACTIVE', 1, 1),
(6, DATE '2026-06-17', TIMESTAMP '2026-06-17 11:28:00', 'cmdr_bravo', 'Sgt. J. Rao', 1, DATE '2026-07-01', 'RETURNED', 3, 1),
(7, DATE '2026-03-13', TIMESTAMP '2026-03-13 13:47:00', 'admin', 'Pvt. A. Khan', 5, NULL, 'ACTIVE', 2, 4),
(8, DATE '2026-01-21', TIMESTAMP '2026-01-21 13:22:00', 'cmdr_bravo', 'Pvt. A. Khan', 2, NULL, 'ACTIVE', 3, 2),
(9, DATE '2026-08-28', TIMESTAMP '2026-08-28 10:59:00', 'cmdr_alpha', 'Lt. N. Kaur', 2, NULL, 'ACTIVE', 1, 2),
(10, DATE '2026-01-06', TIMESTAMP '2026-01-06 10:58:00', 'admin', 'Pvt. A. Khan', 3, NULL, 'ACTIVE', 3, 4),
(11, DATE '2026-03-11', TIMESTAMP '2026-03-11 15:49:00', 'cmdr_bravo', 'Sgt. J. Rao', 6, NULL, 'ACTIVE', 2, 4),
(12, DATE '2026-02-19', TIMESTAMP '2026-02-19 14:47:00', 'admin', 'Sgt. J. Rao', 5, DATE '2026-03-05', 'RETURNED', 2, 4),
(13, DATE '2025-10-31', TIMESTAMP '2025-10-31 15:23:00', 'admin', 'Sgt. J. Rao', 2, NULL, 'ACTIVE', 1, 2),
(14, DATE '2026-06-16', TIMESTAMP '2026-06-16 14:01:00', 'admin', 'Sgt. M. Bose', 6, NULL, 'ACTIVE', 2, 1),
(15, DATE '2026-05-15', TIMESTAMP '2026-05-15 11:25:00', 'admin', 'Sgt. M. Bose', 2, NULL, 'ACTIVE', 1, 2),
(16, DATE '2026-01-26', TIMESTAMP '2026-01-26 12:08:00', 'admin', 'Maj. D. Verma', 2, NULL, 'ACTIVE', 1, 2),
(17, DATE '2026-02-20', TIMESTAMP '2026-02-20 12:28:00', 'admin', 'Cpl. S. Nair', 1, NULL, 'ACTIVE', 3, 1),
(18, DATE '2026-06-04', TIMESTAMP '2026-06-04 15:45:00', 'admin', 'Sgt. J. Rao', 1, DATE '2026-06-18', 'RETURNED', 2, 2);             
CREATE CACHED TABLE "PUBLIC"."AUDIT_LOGS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 106) NOT NULL,
    "ACTION" CHARACTER VARYING(255) NOT NULL,
    "DETAILS" CHARACTER VARYING(500),
    "ROLE" CHARACTER VARYING(255) NOT NULL,
    "STATUS" INTEGER NOT NULL,
    "TIMESTAMP" TIMESTAMP(6) NOT NULL,
    "USERNAME" CHARACTER VARYING(255) NOT NULL
);   
ALTER TABLE "PUBLIC"."AUDIT_LOGS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("ID");    
-- 105 +/- SELECT COUNT(*) FROM PUBLIC.AUDIT_LOGS;             
INSERT INTO "PUBLIC"."AUDIT_LOGS" VALUES
(1, 'GET /api/meta/bases', 'Access denied: Not authenticated', '-', 401, TIMESTAMP '2026-09-29 03:39:16.059168', '-'),
(2, 'POST /api/purchases', 'Weapons x27 for Base Charlie', 'LOGISTICS', 200, TIMESTAMP '2026-09-29 03:39:17.832353', 'logistics01'),
(3, 'POST /api/purchases', 'Protective Gear x39 for Base Charlie', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:17.836563', 'admin'),
(4, 'POST /api/purchases', 'Protective Gear x45 for Base Bravo', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:17.840054', 'admin'),
(5, 'POST /api/purchases', 'Weapons x29 for Base Bravo', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:17.84329', 'admin'),
(6, 'POST /api/purchases', 'Weapons x20 for Base Alpha', 'LOGISTICS', 200, TIMESTAMP '2026-09-29 03:39:17.846484', 'logistics01'),
(7, 'POST /api/purchases', 'Protective Gear x12 for Base Alpha', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:17.850459', 'admin'),
(8, 'POST /api/purchases', 'Protective Gear x44 for Base Charlie', 'LOGISTICS', 200, TIMESTAMP '2026-09-29 03:39:17.855064', 'logistics01'),
(9, 'POST /api/purchases', 'Protective Gear x12 for Base Bravo', 'LOGISTICS', 200, TIMESTAMP '2026-09-29 03:39:17.858539', 'logistics01'),
(10, 'POST /api/purchases', 'Vehicles x2 for Base Bravo', 'LOGISTICS', 200, TIMESTAMP '2026-09-29 03:39:17.861684', 'logistics01'),
(11, 'POST /api/purchases', 'Protective Gear x33 for Base Bravo', 'LOGISTICS', 200, TIMESTAMP '2026-09-29 03:39:17.864744', 'logistics01'),
(12, 'POST /api/purchases', 'Ammunition x857 for Base Alpha', 'LOGISTICS', 200, TIMESTAMP '2026-09-29 03:39:17.868497', 'logistics01'),
(13, 'POST /api/purchases', 'Vehicles x1 for Base Bravo', 'LOGISTICS', 200, TIMESTAMP '2026-09-29 03:39:17.874155', 'logistics01'),
(14, 'POST /api/purchases', 'Vehicles x2 for Base Bravo', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:17.92665', 'admin'),
(15, 'POST /api/purchases', 'Vehicles x1 for Base Bravo', 'LOGISTICS', 200, TIMESTAMP '2026-09-29 03:39:17.931521', 'logistics01'),
(16, 'POST /api/purchases', 'Vehicles x3 for Base Bravo', 'LOGISTICS', 200, TIMESTAMP '2026-09-29 03:39:17.934859', 'logistics01'),
(17, 'POST /api/purchases', 'Ammunition x1206 for Base Charlie', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:17.942966', 'admin'),
(18, 'POST /api/purchases', 'Vehicles x2 for Base Charlie', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:17.94978', 'admin'),
(19, 'POST /api/purchases', 'Vehicles x4 for Base Alpha', 'LOGISTICS', 200, TIMESTAMP '2026-09-29 03:39:17.953548', 'logistics01'),
(20, 'POST /api/purchases', 'Vehicles x4 for Base Charlie', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:17.958968', 'admin'),
(21, 'POST /api/purchases', 'Protective Gear x34 for Base Charlie', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:17.962775', 'admin'),
(22, 'POST /api/purchases', 'Protective Gear x57 for Base Charlie', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:17.966677', 'admin'),
(23, 'POST /api/purchases', 'Protective Gear x37 for Base Alpha', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.02931', 'admin'),
(24, 'POST /api/purchases', 'Vehicles x2 for Base Bravo', 'LOGISTICS', 200, TIMESTAMP '2026-09-29 03:39:18.034118', 'logistics01'),
(25, 'POST /api/purchases', 'Weapons x19 for Base Bravo', 'LOGISTICS', 200, TIMESTAMP '2026-09-29 03:39:18.042965', 'logistics01'),
(26, 'POST /api/purchases', 'Vehicles x3 for Base Charlie', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.048132', 'admin'),
(27, 'POST /api/purchases', 'Protective Gear x56 for Base Charlie', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.053989', 'admin'),
(28, 'POST /api/purchases', 'Weapons x12 for Base Alpha', 'LOGISTICS', 200, TIMESTAMP '2026-09-29 03:39:18.057942', 'logistics01'),
(29, 'POST /api/purchases', 'Vehicles x4 for Base Bravo', 'LOGISTICS', 200, TIMESTAMP '2026-09-29 03:39:18.066932', 'logistics01'),
(30, 'POST /api/purchases', 'Weapons x28 for Base Charlie', 'LOGISTICS', 200, TIMESTAMP '2026-09-29 03:39:18.072011', 'logistics01'),
(31, 'POST /api/purchases', 'Protective Gear x53 for Base Alpha', 'LOGISTICS', 200, TIMESTAMP '2026-09-29 03:39:18.07666', 'logistics01'),
(32, 'POST /api/purchases', 'Ammunition x1176 for Base Charlie', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.132095', 'admin');               
INSERT INTO "PUBLIC"."AUDIT_LOGS" VALUES
(33, 'POST /api/purchases', 'Ammunition x510 for Base Bravo', 'LOGISTICS', 200, TIMESTAMP '2026-09-29 03:39:18.135957', 'logistics01'),
(34, 'POST /api/purchases', 'Ammunition x1199 for Base Alpha', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.140749', 'admin'),
(35, 'POST /api/purchases', 'Ammunition x668 for Base Bravo', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.143994', 'admin'),
(36, 'POST /api/purchases', 'Ammunition x1100 for Base Bravo', 'LOGISTICS', 200, TIMESTAMP '2026-09-29 03:39:18.153549', 'logistics01'),
(37, 'POST /api/purchases', 'Protective Gear x56 for Base Charlie', 'LOGISTICS', 200, TIMESTAMP '2026-09-29 03:39:18.166522', 'logistics01'),
(38, 'POST /api/purchases', 'Weapons x22 for Base Charlie', 'LOGISTICS', 200, TIMESTAMP '2026-09-29 03:39:18.23294', 'logistics01'),
(39, 'POST /api/purchases', 'Ammunition x723 for Base Bravo', 'LOGISTICS', 200, TIMESTAMP '2026-09-29 03:39:18.23682', 'logistics01'),
(40, 'POST /api/purchases', 'Vehicles x4 for Base Alpha', 'LOGISTICS', 200, TIMESTAMP '2026-09-29 03:39:18.243625', 'logistics01'),
(41, 'POST /api/purchases', 'Vehicles x2 for Base Bravo', 'LOGISTICS', 200, TIMESTAMP '2026-09-29 03:39:18.247119', 'logistics01'),
(42, 'POST /api/purchases', 'Vehicles x3 for Base Charlie', 'LOGISTICS', 200, TIMESTAMP '2026-09-29 03:39:18.250316', 'logistics01'),
(43, 'POST /api/purchases', 'Protective Gear x34 for Base Charlie', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.25717', 'admin'),
(44, 'POST /api/transfers', 'Weapons x4: Base Charlie -> Base Bravo', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.266334', 'admin'),
(45, 'POST /api/transfers', 'Weapons x3: Base Charlie -> Base Bravo', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.27049', 'admin'),
(46, 'POST /api/transfers', 'Ammunition x146: Base Bravo -> Base Charlie', 'LOGISTICS', 200, TIMESTAMP '2026-09-29 03:39:18.275154', 'logistics01'),
(47, 'POST /api/transfers', 'Vehicles x1: Base Bravo -> Base Alpha', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.327551', 'admin'),
(48, 'POST /api/transfers', 'Ammunition x288: Base Bravo -> Base Charlie', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.330786', 'admin'),
(49, 'POST /api/transfers', 'Ammunition x448: Base Bravo -> Base Charlie', 'LOGISTICS', 200, TIMESTAMP '2026-09-29 03:39:18.334306', 'logistics01'),
(50, 'POST /api/transfers', 'Weapons x5: Base Charlie -> Base Bravo', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.338397', 'admin'),
(51, 'POST /api/transfers', 'Ammunition x141: Base Bravo -> Base Charlie', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.342119', 'admin'),
(52, 'POST /api/transfers', 'Vehicles x1: Base Alpha -> Base Charlie', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.354229', 'admin'),
(53, 'POST /api/transfers', 'Vehicles x1: Base Alpha -> Base Charlie', 'LOGISTICS', 200, TIMESTAMP '2026-09-29 03:39:18.363219', 'logistics01'),
(54, 'POST /api/transfers', 'Ammunition x567: Base Bravo -> Base Charlie', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.368326', 'admin'),
(55, 'POST /api/transfers', 'Weapons x8: Base Alpha -> Base Bravo', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.372061', 'admin'),
(56, 'POST /api/transfers', 'Protective Gear x10: Base Charlie -> Base Bravo', 'LOGISTICS', 200, TIMESTAMP '2026-09-29 03:39:18.439451', 'logistics01'),
(57, 'POST /api/transfers', 'Vehicles x1: Base Alpha -> Base Bravo', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.44268', 'admin'),
(58, 'POST /api/transfers', 'Ammunition x304: Base Alpha -> Base Bravo', 'LOGISTICS', 200, TIMESTAMP '2026-09-29 03:39:18.446125', 'logistics01'),
(59, 'POST /api/transfers', 'Ammunition x276: Base Bravo -> Base Alpha', 'LOGISTICS', 200, TIMESTAMP '2026-09-29 03:39:18.453769', 'logistics01'),
(60, 'POST /api/transfers', 'Protective Gear x19: Base Alpha -> Base Bravo', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.458117', 'admin'),
(61, 'POST /api/transfers', 'Protective Gear x16: Base Bravo -> Base Alpha', 'LOGISTICS', 200, TIMESTAMP '2026-09-29 03:39:18.463568', 'logistics01'),
(62, 'POST /api/transfers', 'Protective Gear x15: Base Charlie -> Base Bravo', 'LOGISTICS', 200, TIMESTAMP '2026-09-29 03:39:18.466943', 'logistics01'); 
INSERT INTO "PUBLIC"."AUDIT_LOGS" VALUES
(63, 'POST /api/transfers', 'Protective Gear x15: Base Alpha -> Base Bravo', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.470359', 'admin'),
(64, 'POST /api/transfers', 'Ammunition x101: Base Bravo -> Base Alpha', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.478624', 'admin'),
(65, 'POST /api/transfers', 'Weapons x7: Base Alpha -> Base Charlie', 'LOGISTICS', 200, TIMESTAMP '2026-09-29 03:39:18.48267', 'logistics01'),
(66, 'POST /api/transfers', 'Weapons x9: Base Charlie -> Base Bravo', 'LOGISTICS', 200, TIMESTAMP '2026-09-29 03:39:18.485552', 'logistics01'),
(67, 'POST /api/transfers', 'Ammunition x253: Base Bravo -> Base Charlie', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.527418', 'admin'),
(68, 'POST /api/assignments', 'Weapons x3 to Lt. K. Mehta (Base Alpha)', 'COMMANDER', 200, TIMESTAMP '2026-09-29 03:39:18.532097', 'cmdr_alpha'),
(69, 'POST /api/assignments', 'Protective Gear x7 to Pvt. A. Khan (Base Charlie)', 'COMMANDER', 200, TIMESTAMP '2026-09-29 03:39:18.535097', 'cmdr_bravo'),
(70, 'POST /api/assignments', 'Weapons x5 to Pvt. A. Khan (Base Alpha)', 'COMMANDER', 200, TIMESTAMP '2026-09-29 03:39:18.53828', 'cmdr_alpha'),
(71, 'POST /api/assignments', 'Protective Gear x3 to Lt. K. Mehta (Base Alpha)', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.543098', 'admin'),
(72, 'POST /api/assignments', 'Weapons x4 to Sgt. J. Rao (Base Alpha)', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.545935', 'admin'),
(73, 'POST /api/assignments', 'Weapons x1 to Sgt. J. Rao (Base Charlie)', 'COMMANDER', 200, TIMESTAMP '2026-09-29 03:39:18.553067', 'cmdr_bravo'),
(74, 'POST /api/assignments/6/return', 'Weapons x1 returned by Sgt. J. Rao', 'COMMANDER', 200, TIMESTAMP '2026-09-29 03:39:18.555322', 'cmdr_bravo'),
(75, 'POST /api/assignments', 'Protective Gear x5 to Pvt. A. Khan (Base Bravo)', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.558848', 'admin'),
(76, 'POST /api/assignments', 'Vehicles x2 to Pvt. A. Khan (Base Charlie)', 'COMMANDER', 200, TIMESTAMP '2026-09-29 03:39:18.561737', 'cmdr_bravo'),
(77, 'POST /api/assignments', 'Vehicles x2 to Lt. N. Kaur (Base Alpha)', 'COMMANDER', 200, TIMESTAMP '2026-09-29 03:39:18.563988', 'cmdr_alpha'),
(78, 'POST /api/assignments', 'Protective Gear x3 to Pvt. A. Khan (Base Charlie)', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.566596', 'admin'),
(79, 'POST /api/assignments', 'Protective Gear x6 to Sgt. J. Rao (Base Bravo)', 'COMMANDER', 200, TIMESTAMP '2026-09-29 03:39:18.628897', 'cmdr_bravo'),
(80, 'POST /api/assignments', 'Protective Gear x5 to Sgt. J. Rao (Base Bravo)', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.631374', 'admin'),
(81, 'POST /api/assignments/12/return', 'Protective Gear x5 returned by Sgt. J. Rao', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.632835', 'admin'),
(82, 'POST /api/assignments', 'Vehicles x2 to Sgt. J. Rao (Base Alpha)', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.635417', 'admin'),
(83, 'POST /api/assignments', 'Weapons x6 to Sgt. M. Bose (Base Bravo)', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.642039', 'admin'),
(84, 'POST /api/assignments', 'Vehicles x2 to Sgt. M. Bose (Base Alpha)', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.646016', 'admin'),
(85, 'POST /api/assignments', 'Vehicles x2 to Maj. D. Verma (Base Alpha)', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.64906', 'admin'),
(86, 'POST /api/assignments', 'Weapons x1 to Cpl. S. Nair (Base Charlie)', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.651567', 'admin'),
(87, 'POST /api/assignments', 'Vehicles x1 to Sgt. J. Rao (Base Bravo)', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.658757', 'admin'),
(88, 'POST /api/assignments/18/return', 'Vehicles x1 returned by Sgt. J. Rao', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.660548', 'admin'),
(89, 'POST /api/expenditures', 'Vehicles x1 at Base Alpha (Expired stock disposal)', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.664829', 'admin'),
(90, 'POST /api/expenditures', 'Vehicles x1 at Base Alpha (Routine drills)', 'COMMANDER', 200, TIMESTAMP '2026-09-29 03:39:18.667306', 'cmdr_alpha'),
(91, 'POST /api/expenditures', 'Weapons x3 at Base Bravo (Routine drills)', 'COMMANDER', 200, TIMESTAMP '2026-09-29 03:39:18.730779', 'cmdr_bravo');   
INSERT INTO "PUBLIC"."AUDIT_LOGS" VALUES
(92, 'POST /api/expenditures', 'Ammunition x237 at Base Charlie (Routine drills)', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.734133', 'admin'),
(93, 'POST /api/expenditures', 'Vehicles x1 at Base Bravo (Border patrol deployment)', 'COMMANDER', 200, TIMESTAMP '2026-09-29 03:39:18.737153', 'cmdr_bravo'),
(94, 'POST /api/expenditures', 'Vehicles x1 at Base Bravo (Damaged in exercise - written off)', 'COMMANDER', 200, TIMESTAMP '2026-09-29 03:39:18.746042', 'cmdr_bravo'),
(95, 'POST /api/expenditures', 'Ammunition x553 at Base Bravo (Routine drills)', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.748577', 'admin'),
(96, 'POST /api/expenditures', 'Vehicles x1 at Base Charlie (Live-fire training)', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.750931', 'admin'),
(97, 'POST /api/expenditures', 'Ammunition x535 at Base Bravo (Border patrol deployment)', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.756771', 'admin'),
(98, 'POST /api/expenditures', 'Weapons x7 at Base Charlie (Quarterly range practice)', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.760165', 'admin'),
(99, 'POST /api/expenditures', 'Protective Gear x22 at Base Bravo (Quarterly range practice)', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.762744', 'admin'),
(100, 'POST /api/expenditures', 'Protective Gear x6 at Base Alpha (Border patrol deployment)', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.765256', 'admin'),
(101, 'POST /api/expenditures', 'Vehicles x1 at Base Alpha (Damaged in exercise - written off)', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.769468', 'admin'),
(102, 'POST /api/expenditures', 'Weapons x4 at Base Bravo (Expired stock disposal)', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.771922', 'admin'),
(103, 'POST /api/expenditures', 'Weapons x15 at Base Bravo (Routine drills)', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.774466', 'admin'),
(104, 'POST /api/expenditures', 'Ammunition x341 at Base Bravo (Expired stock disposal)', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.826496', 'admin'),
(105, 'SEED', 'Demo data generated (deterministic, seed 42)', 'ADMIN', 200, TIMESTAMP '2026-09-29 03:39:18.828685', 'admin');          
CREATE CACHED TABLE "PUBLIC"."BASES"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 4) NOT NULL,
    "NAME" CHARACTER VARYING(255) NOT NULL
);    
ALTER TABLE "PUBLIC"."BASES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" PRIMARY KEY("ID");         
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.BASES;    
INSERT INTO "PUBLIC"."BASES" VALUES
(1, 'Base Alpha'),
(2, 'Base Bravo'),
(3, 'Base Charlie'); 
CREATE CACHED TABLE "PUBLIC"."EQUIPMENT_TYPES"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 5) NOT NULL,
    "NAME" CHARACTER VARYING(255) NOT NULL
);          
ALTER TABLE "PUBLIC"."EQUIPMENT_TYPES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_B" PRIMARY KEY("ID");               
-- 4 +/- SELECT COUNT(*) FROM PUBLIC.EQUIPMENT_TYPES;          
INSERT INTO "PUBLIC"."EQUIPMENT_TYPES" VALUES
(1, 'Weapons'),
(2, 'Vehicles'),
(3, 'Ammunition'),
(4, 'Protective Gear');      
CREATE CACHED TABLE "PUBLIC"."EXPENDITURES"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 17) NOT NULL,
    "CREATED_AT" TIMESTAMP(6) NOT NULL,
    "CREATED_BY" CHARACTER VARYING(255) NOT NULL,
    "EXPEND_DATE" DATE NOT NULL,
    "QUANTITY" INTEGER NOT NULL,
    "REASON" CHARACTER VARYING(255) NOT NULL,
    "BASE_ID" BIGINT NOT NULL,
    "EQUIPMENT_TYPE_ID" BIGINT NOT NULL
);      
ALTER TABLE "PUBLIC"."EXPENDITURES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_C" PRIMARY KEY("ID");  
-- 16 +/- SELECT COUNT(*) FROM PUBLIC.EXPENDITURES;            
INSERT INTO "PUBLIC"."EXPENDITURES" VALUES
(1, TIMESTAMP '2026-01-19 16:55:00', 'admin', DATE '2026-01-19', 1, 'Expired stock disposal', 1, 2),
(2, TIMESTAMP '2025-10-09 14:24:00', 'cmdr_alpha', DATE '2025-10-09', 1, 'Routine drills', 1, 2),
(3, TIMESTAMP '2026-08-05 12:13:00', 'cmdr_bravo', DATE '2026-08-05', 3, 'Routine drills', 2, 1),
(4, TIMESTAMP '2025-11-19 13:02:00', 'admin', DATE '2025-11-19', 237, 'Routine drills', 3, 3),
(5, TIMESTAMP '2026-05-08 14:16:00', 'cmdr_bravo', DATE '2026-05-08', 1, 'Border patrol deployment', 2, 2),
(6, TIMESTAMP '2026-02-20 14:59:00', 'cmdr_bravo', DATE '2026-02-20', 1, 'Damaged in exercise - written off', 2, 2),
(7, TIMESTAMP '2025-11-10 14:50:00', 'admin', DATE '2025-11-10', 553, 'Routine drills', 2, 3),
(8, TIMESTAMP '2026-09-11 13:00:00', 'admin', DATE '2026-09-11', 1, 'Live-fire training', 3, 2),
(9, TIMESTAMP '2026-06-04 11:11:00', 'admin', DATE '2026-06-04', 535, 'Border patrol deployment', 2, 3),
(10, TIMESTAMP '2026-08-31 17:22:00', 'admin', DATE '2026-08-31', 7, 'Quarterly range practice', 3, 1),
(11, TIMESTAMP '2025-10-18 15:31:00', 'admin', DATE '2025-10-18', 22, 'Quarterly range practice', 2, 4),
(12, TIMESTAMP '2026-05-14 16:23:00', 'admin', DATE '2026-05-14', 6, 'Border patrol deployment', 1, 4),
(13, TIMESTAMP '2026-01-18 18:15:00', 'admin', DATE '2026-01-18', 1, 'Damaged in exercise - written off', 1, 2),
(14, TIMESTAMP '2025-12-23 18:31:00', 'admin', DATE '2025-12-23', 4, 'Expired stock disposal', 2, 1),
(15, TIMESTAMP '2026-08-13 18:49:00', 'admin', DATE '2026-08-13', 15, 'Routine drills', 2, 1),
(16, TIMESTAMP '2026-09-16 11:52:00', 'admin', DATE '2026-09-16', 341, 'Expired stock disposal', 2, 3);            
CREATE CACHED TABLE "PUBLIC"."OPENING_BALANCES"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 13) NOT NULL,
    "QUANTITY" INTEGER NOT NULL,
    "BASE_ID" BIGINT NOT NULL,
    "EQUIPMENT_TYPE_ID" BIGINT NOT NULL
);           
ALTER TABLE "PUBLIC"."OPENING_BALANCES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");              
-- 12 +/- SELECT COUNT(*) FROM PUBLIC.OPENING_BALANCES;        
INSERT INTO "PUBLIC"."OPENING_BALANCES" VALUES
(1, 120, 1, 1),
(2, 25, 1, 2),
(3, 5200, 1, 3),
(4, 210, 1, 4),
(5, 95, 2, 1),
(6, 20, 2, 2),
(7, 4300, 2, 3),
(8, 180, 2, 4),
(9, 140, 3, 1),
(10, 30, 3, 2),
(11, 6100, 3, 3),
(12, 250, 3, 4);               
CREATE CACHED TABLE "PUBLIC"."PURCHASES"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 43) NOT NULL,
    "CREATED_AT" TIMESTAMP(6) NOT NULL,
    "CREATED_BY" CHARACTER VARYING(255) NOT NULL,
    "PURCHASE_DATE" DATE NOT NULL,
    "QUANTITY" INTEGER NOT NULL,
    "SUPPLIER" CHARACTER VARYING(255),
    "UNIT_COST" NUMERIC(12, 2),
    "BASE_ID" BIGINT NOT NULL,
    "EQUIPMENT_TYPE_ID" BIGINT NOT NULL
);              
ALTER TABLE "PUBLIC"."PURCHASES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3B" PRIMARY KEY("ID");    
-- 42 +/- SELECT COUNT(*) FROM PUBLIC.PURCHASES;               
INSERT INTO "PUBLIC"."PURCHASES" VALUES
(1, TIMESTAMP '2026-08-01 11:19:00', 'logistics01', DATE '2026-08-01', 27, 'Bharat Defence Systems', 204000.00, 3, 1),
(2, TIMESTAMP '2026-08-28 15:30:00', 'admin', DATE '2026-08-28', 39, 'Tactical Motors Pvt Ltd', 830400.00, 3, 4),
(3, TIMESTAMP '2026-02-26 09:10:00', 'admin', DATE '2026-02-26', 45, 'SafeGuard Industries', 991200.00, 2, 4),
(4, TIMESTAMP '2025-10-26 11:47:00', 'admin', DATE '2025-10-26', 29, 'Bharat Defence Systems', 247200.00, 2, 1),
(5, TIMESTAMP '2026-03-24 16:35:00', 'logistics01', DATE '2026-03-24', 20, 'SafeGuard Industries', 274800.00, 1, 1),
(6, TIMESTAMP '2026-07-05 17:16:00', 'admin', DATE '2026-07-05', 12, 'Bharat Defence Systems', 831600.00, 1, 4),
(7, TIMESTAMP '2026-06-27 14:32:00', 'logistics01', DATE '2026-06-27', 44, 'Tactical Motors Pvt Ltd', 433200.00, 3, 4),
(8, TIMESTAMP '2026-09-19 10:41:00', 'logistics01', DATE '2026-09-19', 12, 'Ammunition Corp of India', 1042800.00, 2, 4),
(9, TIMESTAMP '2026-06-21 15:00:00', 'logistics01', DATE '2026-06-21', 2, 'Bharat Defence Systems', 583200.00, 2, 2),
(10, TIMESTAMP '2026-05-11 14:19:00', 'logistics01', DATE '2026-05-11', 33, 'Ammunition Corp of India', 471600.00, 2, 4),
(11, TIMESTAMP '2026-09-01 15:56:00', 'logistics01', DATE '2026-09-01', 857, 'Ammunition Corp of India', 2331.00, 1, 3),
(12, TIMESTAMP '2026-02-25 09:26:00', 'logistics01', DATE '2026-02-25', 1, 'Ordnance Factory Board', 214800.00, 2, 2),
(13, TIMESTAMP '2026-02-12 12:46:00', 'admin', DATE '2026-02-12', 2, 'Ordnance Factory Board', 1016400.00, 2, 2),
(14, TIMESTAMP '2026-05-30 17:12:00', 'logistics01', DATE '2026-05-30', 1, 'SafeGuard Industries', 93600.00, 2, 2),
(15, TIMESTAMP '2026-06-25 13:12:00', 'logistics01', DATE '2026-06-25', 3, 'SafeGuard Industries', 362400.00, 2, 2),
(16, TIMESTAMP '2025-11-22 13:23:00', 'admin', DATE '2025-11-22', 1206, 'Tactical Motors Pvt Ltd', 1197.00, 3, 3),
(17, TIMESTAMP '2026-06-11 11:41:00', 'admin', DATE '2026-06-11', 2, 'Bharat Defence Systems', 236400.00, 3, 2),
(18, TIMESTAMP '2026-04-29 13:36:00', 'logistics01', DATE '2026-04-29', 4, 'Ordnance Factory Board', 961200.00, 1, 2),
(19, TIMESTAMP '2026-07-23 13:44:00', 'admin', DATE '2026-07-23', 4, 'Ammunition Corp of India', 756000.00, 3, 2),
(20, TIMESTAMP '2025-12-06 16:22:00', 'admin', DATE '2025-12-06', 34, 'Ordnance Factory Board', 697200.00, 3, 4),
(21, TIMESTAMP '2026-09-15 15:12:00', 'admin', DATE '2026-09-15', 57, 'Ordnance Factory Board', 268800.00, 3, 4),
(22, TIMESTAMP '2025-11-26 14:23:00', 'admin', DATE '2025-11-26', 37, 'Ammunition Corp of India', 453600.00, 1, 4),
(23, TIMESTAMP '2026-03-03 16:42:00', 'logistics01', DATE '2026-03-03', 2, 'Ammunition Corp of India', 1173600.00, 2, 2),
(24, TIMESTAMP '2025-10-16 10:25:00', 'logistics01', DATE '2025-10-16', 19, 'SafeGuard Industries', 1071600.00, 2, 1),
(25, TIMESTAMP '2026-03-23 14:33:00', 'admin', DATE '2026-03-23', 3, 'Ordnance Factory Board', 90000.00, 3, 2),
(26, TIMESTAMP '2026-06-12 13:27:00', 'admin', DATE '2026-06-12', 56, 'Tactical Motors Pvt Ltd', 704400.00, 3, 4),
(27, TIMESTAMP '2026-03-15 09:11:00', 'logistics01', DATE '2026-03-15', 12, 'Ordnance Factory Board', 903600.00, 1, 1),
(28, TIMESTAMP '2025-10-22 09:45:00', 'logistics01', DATE '2025-10-22', 4, 'Bharat Defence Systems', 589200.00, 2, 2),
(29, TIMESTAMP '2026-06-23 13:38:00', 'logistics01', DATE '2026-06-23', 28, 'Bharat Defence Systems', 250800.00, 3, 1),
(30, TIMESTAMP '2026-02-02 09:06:00', 'logistics01', DATE '2026-02-02', 53, 'Tactical Motors Pvt Ltd', 416400.00, 1, 4),
(31, TIMESTAMP '2026-04-15 13:03:00', 'admin', DATE '2026-04-15', 1176, 'Ordnance Factory Board', 7290.00, 3, 3),
(32, TIMESTAMP '2026-05-16 13:08:00', 'logistics01', DATE '2026-05-16', 510, 'Ordnance Factory Board', 5283.00, 2, 3),
(33, TIMESTAMP '2026-02-21 17:03:00', 'admin', DATE '2026-02-21', 1199, 'Tactical Motors Pvt Ltd', 8721.00, 1, 3),
(34, TIMESTAMP '2025-11-17 09:09:00', 'admin', DATE '2025-11-17', 668, 'Ordnance Factory Board', 3051.00, 2, 3),
(35, TIMESTAMP '2026-01-31 17:23:00', 'logistics01', DATE '2026-01-31', 1100, 'Ammunition Corp of India', 6435.00, 2, 3);           
INSERT INTO "PUBLIC"."PURCHASES" VALUES
(36, TIMESTAMP '2025-11-30 12:49:00', 'logistics01', DATE '2025-11-30', 56, 'Bharat Defence Systems', 180000.00, 3, 4),
(37, TIMESTAMP '2026-06-24 14:41:00', 'logistics01', DATE '2026-06-24', 22, 'SafeGuard Industries', 523200.00, 3, 1),
(38, TIMESTAMP '2026-03-17 12:54:00', 'logistics01', DATE '2026-03-17', 723, 'Ordnance Factory Board', 4077.00, 2, 3),
(39, TIMESTAMP '2026-07-01 11:24:00', 'logistics01', DATE '2026-07-01', 4, 'Ammunition Corp of India', 110400.00, 1, 2),
(40, TIMESTAMP '2026-02-18 10:52:00', 'logistics01', DATE '2026-02-18', 2, 'Tactical Motors Pvt Ltd', 994800.00, 2, 2),
(41, TIMESTAMP '2026-02-15 12:56:00', 'logistics01', DATE '2026-02-15', 3, 'Bharat Defence Systems', 787200.00, 3, 2),
(42, TIMESTAMP '2026-03-03 13:14:00', 'admin', DATE '2026-03-03', 34, 'Ordnance Factory Board', 157200.00, 3, 4);         
CREATE CACHED TABLE "PUBLIC"."TRANSFERS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 25) NOT NULL,
    "CREATED_AT" TIMESTAMP(6) NOT NULL,
    "CREATED_BY" CHARACTER VARYING(255) NOT NULL,
    "QUANTITY" INTEGER NOT NULL,
    "REASON" CHARACTER VARYING(255),
    "STATUS" ENUM('COMPLETED') NOT NULL,
    "TRANSFER_DATE" DATE NOT NULL,
    "EQUIPMENT_TYPE_ID" BIGINT NOT NULL,
    "FROM_BASE_ID" BIGINT NOT NULL,
    "TO_BASE_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."TRANSFERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E4" PRIMARY KEY("ID");    
-- 24 +/- SELECT COUNT(*) FROM PUBLIC.TRANSFERS;               
INSERT INTO "PUBLIC"."TRANSFERS" VALUES
(1, TIMESTAMP '2026-03-17 10:47:00', 'admin', 4, 'Reinforcement', 'COMPLETED', DATE '2026-03-17', 1, 3, 2),
(2, TIMESTAMP '2026-07-30 16:29:00', 'admin', 3, NULL, 'COMPLETED', DATE '2026-07-30', 1, 3, 2),
(3, TIMESTAMP '2026-05-16 11:37:00', 'logistics01', 146, NULL, 'COMPLETED', DATE '2026-05-16', 3, 2, 3),
(4, TIMESTAMP '2026-02-11 08:22:00', 'admin', 1, 'Reinforcement', 'COMPLETED', DATE '2026-02-11', 2, 2, 1),
(5, TIMESTAMP '2026-03-08 16:47:00', 'admin', 288, NULL, 'COMPLETED', DATE '2026-03-08', 3, 2, 3),
(6, TIMESTAMP '2026-08-20 12:55:00', 'logistics01', 448, NULL, 'COMPLETED', DATE '2026-08-20', 3, 2, 3),
(7, TIMESTAMP '2025-10-30 09:28:00', 'admin', 5, 'Reinforcement', 'COMPLETED', DATE '2025-10-30', 1, 3, 2),
(8, TIMESTAMP '2025-12-09 12:38:00', 'admin', 141, NULL, 'COMPLETED', DATE '2025-12-09', 3, 2, 3),
(9, TIMESTAMP '2026-05-31 09:42:00', 'admin', 1, NULL, 'COMPLETED', DATE '2026-05-31', 2, 1, 3),
(10, TIMESTAMP '2026-05-06 12:01:00', 'logistics01', 1, 'Reinforcement', 'COMPLETED', DATE '2026-05-06', 2, 1, 3),
(11, TIMESTAMP '2026-08-26 16:57:00', 'admin', 567, NULL, 'COMPLETED', DATE '2026-08-26', 3, 2, 3),
(12, TIMESTAMP '2026-02-07 15:36:00', 'admin', 8, NULL, 'COMPLETED', DATE '2026-02-07', 1, 1, 2),
(13, TIMESTAMP '2025-12-15 15:38:00', 'logistics01', 10, 'Reinforcement', 'COMPLETED', DATE '2025-12-15', 4, 3, 2),
(14, TIMESTAMP '2025-11-16 14:01:00', 'admin', 1, NULL, 'COMPLETED', DATE '2025-11-16', 2, 1, 2),
(15, TIMESTAMP '2026-03-23 12:24:00', 'logistics01', 304, NULL, 'COMPLETED', DATE '2026-03-23', 3, 1, 2),
(16, TIMESTAMP '2026-08-28 08:30:00', 'logistics01', 276, 'Reinforcement', 'COMPLETED', DATE '2026-08-28', 3, 2, 1),
(17, TIMESTAMP '2026-04-08 12:34:00', 'admin', 19, NULL, 'COMPLETED', DATE '2026-04-08', 4, 1, 2),
(18, TIMESTAMP '2025-11-23 16:34:00', 'logistics01', 16, NULL, 'COMPLETED', DATE '2025-11-23', 4, 2, 1),
(19, TIMESTAMP '2026-01-16 16:42:00', 'logistics01', 15, 'Reinforcement', 'COMPLETED', DATE '2026-01-16', 4, 3, 2),
(20, TIMESTAMP '2026-04-15 08:15:00', 'admin', 15, NULL, 'COMPLETED', DATE '2026-04-15', 4, 1, 2),
(21, TIMESTAMP '2026-05-28 08:06:00', 'admin', 101, NULL, 'COMPLETED', DATE '2026-05-28', 3, 2, 1),
(22, TIMESTAMP '2026-02-21 11:16:00', 'logistics01', 7, 'Reinforcement', 'COMPLETED', DATE '2026-02-21', 1, 1, 3),
(23, TIMESTAMP '2026-06-24 16:09:00', 'logistics01', 9, NULL, 'COMPLETED', DATE '2026-06-24', 1, 3, 2),
(24, TIMESTAMP '2026-01-02 15:32:00', 'admin', 253, NULL, 'COMPLETED', DATE '2026-01-02', 3, 2, 3);      
CREATE CACHED TABLE "PUBLIC"."USERS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 5) NOT NULL,
    "PASSWORD_HASH" CHARACTER VARYING(255) NOT NULL,
    "ROLE" ENUM('ADMIN', 'COMMANDER', 'LOGISTICS') NOT NULL,
    "USERNAME" CHARACTER VARYING(255) NOT NULL,
    "BASE_ID" BIGINT
);        
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4D" PRIMARY KEY("ID");        
-- 4 +/- SELECT COUNT(*) FROM PUBLIC.USERS;    
INSERT INTO "PUBLIC"."USERS" VALUES
(1, '$2a$10$CGVAEi8boUrz5YoDTEbvy.0mZh6y1bweuUpnq7YVpqCSOXs8uC52S', 'ADMIN', 'admin', NULL),
(2, '$2a$10$zlX3d7Bif8HEY95tagc1pOTgskosPgHb..bPUim8iEuC292OmilDa', 'COMMANDER', 'cmdr_alpha', 1),
(3, '$2a$10$H/Y.dcgQ/FsCxVAyeVm6vefKUek1038mdmACBbFmzSrHL2UvXqL5m', 'COMMANDER', 'cmdr_bravo', 2),
(4, '$2a$10$oDTx5EfXNTddMoTdvLS0feT2rxJ3Bd7opuRVwPhswrs4tfurcBvze', 'LOGISTICS', 'logistics01', NULL);  
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."UKR43AF9AP4EDM43MMTQ01ODDJ6" UNIQUE("USERNAME");         
ALTER TABLE "PUBLIC"."BASES" ADD CONSTRAINT "PUBLIC"."UKJI1WUJYTMFP28MST0MRQO6AA2" UNIQUE("NAME");             
ALTER TABLE "PUBLIC"."OPENING_BALANCES" ADD CONSTRAINT "PUBLIC"."UKJ44D4TEJ0CMP4WDDWKQ5HJKFE" UNIQUE("BASE_ID", "EQUIPMENT_TYPE_ID");          
ALTER TABLE "PUBLIC"."EQUIPMENT_TYPES" ADD CONSTRAINT "PUBLIC"."UKHPLMO7AXIED1HALM0JDVB0S6J" UNIQUE("NAME");   
ALTER TABLE "PUBLIC"."TRANSFERS" ADD CONSTRAINT "PUBLIC"."FKCYR8V4236KSY6J4HU9HXVSM86" FOREIGN KEY("EQUIPMENT_TYPE_ID") REFERENCES "PUBLIC"."EQUIPMENT_TYPES"("ID") NOCHECK;   
ALTER TABLE "PUBLIC"."OPENING_BALANCES" ADD CONSTRAINT "PUBLIC"."FKAFGSY3T4EN2U8FLMOGF2S2YVR" FOREIGN KEY("EQUIPMENT_TYPE_ID") REFERENCES "PUBLIC"."EQUIPMENT_TYPES"("ID") NOCHECK;            
ALTER TABLE "PUBLIC"."ASSIGNMENTS" ADD CONSTRAINT "PUBLIC"."FKGFK2JWGV985IL072CUYT95997" FOREIGN KEY("EQUIPMENT_TYPE_ID") REFERENCES "PUBLIC"."EQUIPMENT_TYPES"("ID") NOCHECK; 
ALTER TABLE "PUBLIC"."OPENING_BALANCES" ADD CONSTRAINT "PUBLIC"."FKQ87K7GAP7GCI3D7TCL3A9CNJV" FOREIGN KEY("BASE_ID") REFERENCES "PUBLIC"."BASES"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."ASSIGNMENTS" ADD CONSTRAINT "PUBLIC"."FKM52V5EMJ0S4CH6QYQHF6OLTU0" FOREIGN KEY("BASE_ID") REFERENCES "PUBLIC"."BASES"("ID") NOCHECK;     
ALTER TABLE "PUBLIC"."EXPENDITURES" ADD CONSTRAINT "PUBLIC"."FKEGUDIP6R0GTCPYHD9NU5BOJGR" FOREIGN KEY("BASE_ID") REFERENCES "PUBLIC"."BASES"("ID") NOCHECK;    
ALTER TABLE "PUBLIC"."TRANSFERS" ADD CONSTRAINT "PUBLIC"."FKEY2FNRJF4TTHAC9VMJV4P37T4" FOREIGN KEY("FROM_BASE_ID") REFERENCES "PUBLIC"."BASES"("ID") NOCHECK;  
ALTER TABLE "PUBLIC"."TRANSFERS" ADD CONSTRAINT "PUBLIC"."FKBYGUJO0ME1KWIDPH3R3WI6PPE" FOREIGN KEY("TO_BASE_ID") REFERENCES "PUBLIC"."BASES"("ID") NOCHECK;    
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."FK42VYE4LLCSJLHU40LUXER3S2Q" FOREIGN KEY("BASE_ID") REFERENCES "PUBLIC"."BASES"("ID") NOCHECK;           
ALTER TABLE "PUBLIC"."PURCHASES" ADD CONSTRAINT "PUBLIC"."FKL8WNAPCIQ105WI29V1WAR8YST" FOREIGN KEY("EQUIPMENT_TYPE_ID") REFERENCES "PUBLIC"."EQUIPMENT_TYPES"("ID") NOCHECK;   
ALTER TABLE "PUBLIC"."EXPENDITURES" ADD CONSTRAINT "PUBLIC"."FKIAE0NHA50G0OG2D3CC356YY85" FOREIGN KEY("EQUIPMENT_TYPE_ID") REFERENCES "PUBLIC"."EQUIPMENT_TYPES"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."PURCHASES" ADD CONSTRAINT "PUBLIC"."FKFTUBICNKDKJXJ8DXBDFH15EXN" FOREIGN KEY("BASE_ID") REFERENCES "PUBLIC"."BASES"("ID") NOCHECK;       
